spring.output.ansi.enabled=always
server.port=8080
spring.application.name=api-gateway

# Localizador Automático de Eureka
spring.cloud.gateway.discovery.locator.enabled=true

# Configuración correcta de la ruta para Flotas (Todo con índice)
spring.cloud.gateway.routes[0].id=flota-route
spring.cloud.gateway.routes[0].uri=lb://FLOTA-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/flota/**

# Conexión a Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
