spring.application.name=service-cotizador
spring.output.ansi.enabled=always

server.port=8082

# Tarifas configurables
tarifa.moto=500
tarifa.carro=1200
tarifa.camion=2500
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/



