spring.application.name=flota-service
spring.output.ansi.enabled=always

server.port=8083

# URLs de los microservicios externos
servicio.vehiculo.url=http://localhost:8081
servicio.cotizador.url=http://localhost:8082

